# Generated by Django 4.2.2 on 2023-06-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_delete_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
